allow-branch = ["main"]
publish = false
tag = false
push = false
pre-release-commit-message = "chore: bump {{crate_name}} version to {{version}}"
pre-release-replacements = [
  { file = "extension/manifest.json", search = '"version": "[^"]+"', replace = '"version": "{{version}}"', exactly = 1 },
]
tag-name = "v{{version}}"
tag-message = "v{{version}}"
